# Generated by Django 6.0.6 on 2026-06-26 04:39

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_verified_profile_pitch_deck_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_views', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartupAnalysis',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_analysis', models.TextField(blank=True)),
                ('swot_analysis', models.TextField(blank=True)),
                ('financial_roadmap', models.TextField(blank=True)),
                ('growth_strategy', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
