# Generated by Django 6.0.6 on 2026-06-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_notification_user_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupanalysis',
            name='competition_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startupanalysis',
            name='marketing_tactics',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startupanalysis',
            name='operational_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startupanalysis',
            name='revenue_model',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startupanalysis',
            name='risk_assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startupanalysis',
            name='target_audience',
            field=models.TextField(blank=True),
        ),
    ]
