# Generated by Django 5.2.3 on 2026-06-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='raised_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
