# Generated by Django 5.2.3 on 2026-06-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_email_otp_profile_last_otp_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='failed_otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_otp_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
