# Generated by Django 5.2.3 on 2026-07-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reports_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_type',
            field=models.CharField(default='free', max_length=20),
        ),
    ]
