# Generated by Django 5.2.3 on 2026-07-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_request_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
