# Generated by Django 6.0.6 on 2026-08-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
