# Generated by Django 5.2.3 on 2026-07-07 07:57

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('pitch', models.TextField()),
                ('report_json', models.TextField()),
                ('report_title', models.CharField(blank=True, max_length=300)),
                ('premium', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='reports_rep_user_id_dcf374_idx'), models.Index(fields=['user', 'deleted'], name='reports_rep_user_id_924771_idx')],
            },
        ),
    ]
