# Generated by Django 5.2.3 on 2026-07-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
